// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyrdr_7rjvLIFBNG5lnmR-Mu8DFR1NjYc',
    appId: '1:823090500276:web:87766c8be27f3d1abb7de1',
    messagingSenderId: '823090500276',
    projectId: 'codingtask-9aeec',
    authDomain: 'codingtask-9aeec.firebaseapp.com',
    storageBucket: 'codingtask-9aeec.appspot.com',
    measurementId: 'G-4CEK0TQRQ7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBp4hMKfc1-ean-k3_9UcFehvbBTSa9f48',
    appId: '1:823090500276:android:d6b1340a828ea4dabb7de1',
    messagingSenderId: '823090500276',
    projectId: 'codingtask-9aeec',
    storageBucket: 'codingtask-9aeec.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-drOan1_coqBkhT3Tv2HTdw48rH3n92Y',
    appId: '1:823090500276:ios:cb7073f726f16073bb7de1',
    messagingSenderId: '823090500276',
    projectId: 'codingtask-9aeec',
    storageBucket: 'codingtask-9aeec.appspot.com',
    iosBundleId: 'com.example.codingTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-drOan1_coqBkhT3Tv2HTdw48rH3n92Y',
    appId: '1:823090500276:ios:cb7073f726f16073bb7de1',
    messagingSenderId: '823090500276',
    projectId: 'codingtask-9aeec',
    storageBucket: 'codingtask-9aeec.appspot.com',
    iosBundleId: 'com.example.codingTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDyrdr_7rjvLIFBNG5lnmR-Mu8DFR1NjYc',
    appId: '1:823090500276:web:496ff137461723fdbb7de1',
    messagingSenderId: '823090500276',
    projectId: 'codingtask-9aeec',
    authDomain: 'codingtask-9aeec.firebaseapp.com',
    storageBucket: 'codingtask-9aeec.appspot.com',
    measurementId: 'G-86CLK31TJB',
  );
}
